stages:
  - stage1
  - stage2

jobs:
  - jobName: k6_pipeline_stop_job_a
    stage: stage1
    executions:
      - type: INSERT
        name: k6_pipeline_stop_job_insert_a
        sql: select * from test_stop_job_source_a order by id asc
        destTable: test_stop_job_dest_a
    setting:
      fetchSize: 5
      batchSize: 5
      atomicLevel: JOB
    database:
      source:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data
        username: sa
        password: "sa"
      dest:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data
        username: sa
        password: "sa"
  - jobName: k6_pipeline_stop_job_b
    stage: stage2
    executions:
      - type: INSERT
        name: k6_pipeline_stop_job_insert_b
        sql: select * from test_stop_job_source_b order by id asc
        destTable: test_stop_job_dest_b
    setting:
      fetchSize: 100
      batchSize: 100
      atomicLevel: JOB
    database:
      source:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data
        username: sa
        password: "sa"
      dest:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data
        username: sa
        password: "sa"
