stages:
  - stage1

jobs:
  - jobName: sync-watermark
    stage: stage1
    setting:
      fetchSize: 100
      batchSize: 10
      atomicLevel: JOB
    database:
      source:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
      dest:
        driver: org.h2.Driver
        url: jdbc:h2:./h2data/data;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
    executions:
      - type: INSERT
        name: k6_watermark_test
        sql: |
          SELECT id, name, update_time 
          FROM source_watermark
          WHERE update_time > :_LAST_WATERMARK
        destTable: dest_watermark
        parameters: 
          - param: _LAST_WATERMARK
            value: "1970-01-01 00:00:00"
            type: timestamp
        watermarkColumn: UPDATE_TIME
