CREATE TABLE iris_pipeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_path VARCHAR(1000) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_iris_pipeline_config_path UNIQUE (config_path)
);

CREATE TABLE iris_pipeline_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    fetch_size INT,
    batch_size INT,
    delete_threshold INT,
    atomic_level VARCHAR(20) NOT NULL,
    CONSTRAINT fk_iris_pipeline_job_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES iris_pipeline(id),
    CONSTRAINT uk_iris_pipeline_job_order UNIQUE (pipeline_id, sequence_order)
);

CREATE TABLE iris_pipeline_job_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    connection_role VARCHAR(20) NOT NULL,
    driver VARCHAR(255) NOT NULL,
    url VARCHAR(2000) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_iris_pipeline_job_connection_job
        FOREIGN KEY (job_id) REFERENCES iris_pipeline_job(id),
    CONSTRAINT uk_iris_pipeline_job_connection_role UNIQUE (job_id, connection_role)
);

CREATE TABLE iris_pipeline_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    execution_name VARCHAR(255),
    execution_type VARCHAR(20) NOT NULL,
    sql_statement CLOB NOT NULL,
    dest_table VARCHAR(255),
    watermark_column VARCHAR(255),
    CONSTRAINT fk_iris_pipeline_execution_job
        FOREIGN KEY (job_id) REFERENCES iris_pipeline_job(id),
    CONSTRAINT uk_iris_pipeline_execution_order UNIQUE (job_id, sequence_order)
);

CREATE TABLE iris_pipeline_execution_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    param_name VARCHAR(255) NOT NULL,
    param_value CLOB,
    param_type VARCHAR(50),
    CONSTRAINT fk_iris_pipeline_execution_parameter_execution
        FOREIGN KEY (execution_id) REFERENCES iris_pipeline_execution(id),
    CONSTRAINT uk_iris_pipeline_execution_parameter_order UNIQUE (execution_id, sequence_order)
);

CREATE INDEX idx_iris_pipeline_job_pipeline_id
    ON iris_pipeline_job (pipeline_id);

CREATE INDEX idx_iris_pipeline_job_connection_job_id
    ON iris_pipeline_job_connection (job_id);

CREATE INDEX idx_iris_pipeline_execution_job_id
    ON iris_pipeline_execution (job_id);

CREATE INDEX idx_iris_pipeline_execution_parameter_execution_id
    ON iris_pipeline_execution_parameter (execution_id);
