CREATE TABLE iris_workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_key VARCHAR(128) NOT NULL,
    workspace_name VARCHAR(255) NOT NULL,
    system_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_iris_workspace_key UNIQUE (workspace_key)
);

CREATE INDEX idx_iris_workspace_system_default
    ON iris_workspace (system_default);

INSERT INTO iris_workspace (
    workspace_key,
    workspace_name,
    system_default,
    created_at,
    updated_at
) VALUES (
    'default',
    'Default Workspace',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

CREATE TABLE iris_pipeline_folder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    parent_id BIGINT,
    folder_name VARCHAR(255) NOT NULL,
    system_root BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_folder_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id),
    CONSTRAINT fk_iris_pipeline_folder_parent
        FOREIGN KEY (parent_id) REFERENCES iris_pipeline_folder(id),
    CONSTRAINT uk_iris_pipeline_folder_parent_name UNIQUE (parent_id, folder_name)
);

CREATE INDEX idx_iris_pipeline_folder_workspace_id
    ON iris_pipeline_folder (workspace_id);

CREATE INDEX idx_iris_pipeline_folder_parent_id
    ON iris_pipeline_folder (parent_id);

INSERT INTO iris_pipeline_folder (
    workspace_id,
    parent_id,
    folder_name,
    system_root,
    created_at,
    updated_at
) VALUES (
    (SELECT id FROM iris_workspace WHERE workspace_key = 'default'),
    NULL,
    '__root__',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

CREATE TABLE iris_pipeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    folder_id BIGINT NOT NULL,
    pipeline_name VARCHAR(255) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id),
    CONSTRAINT fk_iris_pipeline_folder
        FOREIGN KEY (folder_id) REFERENCES iris_pipeline_folder(id),
    CONSTRAINT uk_iris_pipeline_folder_name UNIQUE (folder_id, pipeline_name)
);

CREATE INDEX idx_iris_pipeline_workspace_id
    ON iris_pipeline (workspace_id);

CREATE INDEX idx_iris_pipeline_folder_id
    ON iris_pipeline (folder_id);

CREATE TABLE iris_pipeline_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    fetch_size INT,
    batch_size INT,
    delete_threshold INT,
    atomic_level VARCHAR(20) NOT NULL,
    CONSTRAINT fk_iris_pipeline_job_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES iris_pipeline(id),
    CONSTRAINT uk_iris_pipeline_job_order UNIQUE (pipeline_id, sequence_order)
);

CREATE INDEX idx_iris_pipeline_job_pipeline_id
    ON iris_pipeline_job (pipeline_id);

CREATE TABLE iris_pipeline_job_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    connection_role VARCHAR(20) NOT NULL,
    driver VARCHAR(255) NOT NULL,
    url VARCHAR(2000) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_iris_pipeline_job_connection_job
        FOREIGN KEY (job_id) REFERENCES iris_pipeline_job(id),
    CONSTRAINT uk_iris_pipeline_job_connection_role UNIQUE (job_id, connection_role)
);

CREATE INDEX idx_iris_pipeline_job_connection_job_id
    ON iris_pipeline_job_connection (job_id);

CREATE TABLE iris_pipeline_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    execution_name VARCHAR(255),
    execution_type VARCHAR(20) NOT NULL,
    sql_statement CLOB NOT NULL,
    dest_table VARCHAR(255),
    watermark_column VARCHAR(255),
    CONSTRAINT fk_iris_pipeline_execution_job
        FOREIGN KEY (job_id) REFERENCES iris_pipeline_job(id),
    CONSTRAINT uk_iris_pipeline_execution_order UNIQUE (job_id, sequence_order)
);

CREATE INDEX idx_iris_pipeline_execution_job_id
    ON iris_pipeline_execution (job_id);

CREATE TABLE iris_pipeline_execution_parameter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT NOT NULL,
    sequence_order INT NOT NULL,
    param_name VARCHAR(255) NOT NULL,
    param_value CLOB,
    param_type VARCHAR(50),
    CONSTRAINT fk_iris_pipeline_execution_parameter_execution
        FOREIGN KEY (execution_id) REFERENCES iris_pipeline_execution(id),
    CONSTRAINT uk_iris_pipeline_execution_parameter_order UNIQUE (execution_id, sequence_order)
);

CREATE INDEX idx_iris_pipeline_execution_parameter_execution_id
    ON iris_pipeline_execution_parameter (execution_id);

CREATE TABLE iris_pipeline_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    pipeline_id BIGINT NOT NULL,
    rerun_from_pipeline_run_id BIGINT,
    latest_execution_id BIGINT,
    requested_async BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id),
    CONSTRAINT fk_iris_pipeline_run_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES iris_pipeline(id),
    CONSTRAINT fk_iris_pipeline_run_rerun_from
        FOREIGN KEY (rerun_from_pipeline_run_id) REFERENCES iris_pipeline_run(id)
);

CREATE INDEX idx_iris_pipeline_run_workspace_id
    ON iris_pipeline_run (workspace_id);

CREATE INDEX idx_iris_pipeline_run_workspace_id_id_desc
    ON iris_pipeline_run (workspace_id, id DESC);

CREATE INDEX idx_iris_pipeline_run_pipeline_id
    ON iris_pipeline_run (pipeline_id);

CREATE TABLE iris_pipeline_run_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    execution_no INT NOT NULL,
    execution_kind VARCHAR(20) NOT NULL,
    requested_async BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_execution_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_execution_no UNIQUE (pipeline_run_id, execution_no)
);

CREATE INDEX idx_iris_pipeline_run_execution_run_id
    ON iris_pipeline_run_execution (pipeline_run_id);

ALTER TABLE iris_pipeline_run
    ADD CONSTRAINT fk_iris_pipeline_run_latest_execution
        FOREIGN KEY (latest_execution_id) REFERENCES iris_pipeline_run_execution(id);

CREATE TABLE iris_pipeline_run_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    job_sequence_order INT NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    atomic_level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    root_job_instance_id BIGINT,
    last_job_execution_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_job_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_job_order UNIQUE (pipeline_run_id, job_sequence_order)
);

CREATE INDEX idx_iris_pipeline_run_job_run_id
    ON iris_pipeline_run_job (pipeline_run_id);

CREATE INDEX idx_iris_pipeline_run_job_last_execution_id
    ON iris_pipeline_run_job (last_job_execution_id);

CREATE TABLE iris_pipeline_run_execution_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_execution_id BIGINT NOT NULL,
    pipeline_run_job_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    root_job_instance_id BIGINT,
    last_job_execution_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_execution_job_execution
        FOREIGN KEY (pipeline_run_execution_id) REFERENCES iris_pipeline_run_execution(id),
    CONSTRAINT fk_iris_pipeline_run_execution_job_run_job
        FOREIGN KEY (pipeline_run_job_id) REFERENCES iris_pipeline_run_job(id),
    CONSTRAINT uk_iris_pipeline_run_execution_job UNIQUE (pipeline_run_execution_id, pipeline_run_job_id)
);

CREATE INDEX idx_iris_pipeline_run_execution_job_execution_id
    ON iris_pipeline_run_execution_job (pipeline_run_execution_id);

CREATE INDEX idx_iris_pipeline_run_execution_job_run_job_id
    ON iris_pipeline_run_execution_job (pipeline_run_job_id);

CREATE INDEX idx_iris_pipeline_run_execution_job_last_execution_id
    ON iris_pipeline_run_execution_job (last_job_execution_id);

CREATE TABLE iris_pipeline_run_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    snapshot_schema_version INT NOT NULL,
    pipeline_content_hash VARCHAR(64) NOT NULL,
    materialized_job_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_snapshot_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_snapshot_run UNIQUE (pipeline_run_id)
);

CREATE INDEX idx_iris_pipeline_run_snapshot_run_id
    ON iris_pipeline_run_snapshot (pipeline_run_id);
