CREATE TABLE iris_pipeline_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    requested_async BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_pipeline
        FOREIGN KEY (pipeline_id) REFERENCES iris_pipeline(id)
);

CREATE TABLE iris_pipeline_run_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    job_sequence_order INT NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    atomic_level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    root_job_instance_id BIGINT,
    last_job_execution_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_job_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_job_order UNIQUE (pipeline_run_id, job_sequence_order)
);

CREATE INDEX idx_iris_pipeline_run_pipeline_id
    ON iris_pipeline_run (pipeline_id);

CREATE INDEX idx_iris_pipeline_run_job_run_id
    ON iris_pipeline_run_job (pipeline_run_id);

CREATE INDEX idx_iris_pipeline_run_job_last_execution_id
    ON iris_pipeline_run_job (last_job_execution_id);
