CREATE TABLE iris_pipeline_run_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    snapshot_schema_version INT NOT NULL,
    pipeline_content_hash VARCHAR(64) NOT NULL,
    materialized_job_json CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_snapshot_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_snapshot_run UNIQUE (pipeline_run_id)
);

CREATE INDEX idx_iris_pipeline_run_snapshot_run_id
    ON iris_pipeline_run_snapshot (pipeline_run_id);
