ALTER TABLE iris_pipeline_run
    ADD rerun_from_pipeline_run_id BIGINT;

ALTER TABLE iris_pipeline_run
    ADD latest_execution_id BIGINT;

CREATE TABLE iris_pipeline_run_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL,
    execution_no INT NOT NULL,
    execution_kind VARCHAR(20) NOT NULL,
    requested_async BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_execution_run
        FOREIGN KEY (pipeline_run_id) REFERENCES iris_pipeline_run(id),
    CONSTRAINT uk_iris_pipeline_run_execution_no UNIQUE (pipeline_run_id, execution_no)
);

CREATE TABLE iris_pipeline_run_execution_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_execution_id BIGINT NOT NULL,
    pipeline_run_job_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    root_job_instance_id BIGINT,
    last_job_execution_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_run_execution_job_execution
        FOREIGN KEY (pipeline_run_execution_id) REFERENCES iris_pipeline_run_execution(id),
    CONSTRAINT fk_iris_pipeline_run_execution_job_run_job
        FOREIGN KEY (pipeline_run_job_id) REFERENCES iris_pipeline_run_job(id),
    CONSTRAINT uk_iris_pipeline_run_execution_job UNIQUE (pipeline_run_execution_id, pipeline_run_job_id)
);

CREATE INDEX idx_iris_pipeline_run_execution_run_id
    ON iris_pipeline_run_execution (pipeline_run_id);

CREATE INDEX idx_iris_pipeline_run_execution_job_execution_id
    ON iris_pipeline_run_execution_job (pipeline_run_execution_id);

CREATE INDEX idx_iris_pipeline_run_execution_job_run_job_id
    ON iris_pipeline_run_execution_job (pipeline_run_job_id);

CREATE INDEX idx_iris_pipeline_run_execution_job_last_execution_id
    ON iris_pipeline_run_execution_job (last_job_execution_id);

INSERT INTO iris_pipeline_run_execution (
    pipeline_run_id,
    execution_no,
    execution_kind,
    requested_async,
    status,
    created_at,
    start_time,
    end_time,
    updated_at
)
SELECT
    pr.id,
    1,
    'INITIAL',
    COALESCE(pr.requested_async, FALSE),
    pr.status,
    pr.created_at,
    pr.start_time,
    pr.end_time,
    pr.updated_at
FROM iris_pipeline_run pr
WHERE NOT EXISTS (
    SELECT 1
    FROM iris_pipeline_run_execution pre
    WHERE pre.pipeline_run_id = pr.id
);

INSERT INTO iris_pipeline_run_execution_job (
    pipeline_run_execution_id,
    pipeline_run_job_id,
    status,
    root_job_instance_id,
    last_job_execution_id,
    created_at,
    start_time,
    end_time,
    updated_at
)
SELECT
    pre.id,
    prj.id,
    prj.status,
    prj.root_job_instance_id,
    prj.last_job_execution_id,
    prj.created_at,
    prj.start_time,
    prj.end_time,
    prj.updated_at
FROM iris_pipeline_run_job prj
JOIN iris_pipeline_run_execution pre
    ON pre.pipeline_run_id = prj.pipeline_run_id
    AND pre.execution_no = 1
WHERE NOT EXISTS (
    SELECT 1
    FROM iris_pipeline_run_execution_job prej
    WHERE prej.pipeline_run_execution_id = pre.id
      AND prej.pipeline_run_job_id = prj.id
);

UPDATE iris_pipeline_run pr
SET latest_execution_id = (
    SELECT pre.id
    FROM iris_pipeline_run_execution pre
    WHERE pre.pipeline_run_id = pr.id
      AND pre.execution_no = (
          SELECT MAX(pre2.execution_no)
          FROM iris_pipeline_run_execution pre2
          WHERE pre2.pipeline_run_id = pr.id
      )
);

ALTER TABLE iris_pipeline_run
    ADD CONSTRAINT fk_iris_pipeline_run_rerun_from
        FOREIGN KEY (rerun_from_pipeline_run_id) REFERENCES iris_pipeline_run(id);

ALTER TABLE iris_pipeline_run
    ADD CONSTRAINT fk_iris_pipeline_run_latest_execution
        FOREIGN KEY (latest_execution_id) REFERENCES iris_pipeline_run_execution(id);
