CREATE TABLE iris_pipeline_folder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    folder_name VARCHAR(255) NOT NULL,
    system_root BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_iris_pipeline_folder_parent
        FOREIGN KEY (parent_id) REFERENCES iris_pipeline_folder(id),
    CONSTRAINT uk_iris_pipeline_folder_parent_name UNIQUE (parent_id, folder_name)
);

CREATE INDEX idx_iris_pipeline_folder_parent_id
    ON iris_pipeline_folder (parent_id);

INSERT INTO iris_pipeline_folder (
    parent_id,
    folder_name,
    system_root,
    created_at,
    updated_at
) VALUES (
    NULL,
    '__root__',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

ALTER TABLE iris_pipeline
    ADD COLUMN folder_id BIGINT;

ALTER TABLE iris_pipeline
    ADD COLUMN pipeline_name VARCHAR(255);

UPDATE iris_pipeline
SET folder_id = (
        SELECT id
        FROM iris_pipeline_folder
        WHERE system_root = TRUE
    ),
    pipeline_name = REGEXP_REPLACE(config_path, '^.*/', '');

ALTER TABLE iris_pipeline
    ALTER COLUMN folder_id SET NOT NULL;

ALTER TABLE iris_pipeline
    ALTER COLUMN pipeline_name SET NOT NULL;

ALTER TABLE iris_pipeline
    ADD CONSTRAINT fk_iris_pipeline_folder
        FOREIGN KEY (folder_id) REFERENCES iris_pipeline_folder(id);

ALTER TABLE iris_pipeline
    ADD CONSTRAINT uk_iris_pipeline_folder_name UNIQUE (folder_id, pipeline_name);

CREATE INDEX idx_iris_pipeline_folder_id
    ON iris_pipeline (folder_id);
