CREATE TABLE iris_workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_key VARCHAR(128) NOT NULL,
    workspace_name VARCHAR(255) NOT NULL,
    system_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_iris_workspace_key UNIQUE (workspace_key)
);

CREATE INDEX idx_iris_workspace_system_default
    ON iris_workspace (system_default);

INSERT INTO iris_workspace (
    workspace_key,
    workspace_name,
    system_default,
    created_at,
    updated_at
) VALUES (
    'default',
    'Default Workspace',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

ALTER TABLE iris_pipeline_folder
    ADD COLUMN workspace_id BIGINT;

UPDATE iris_pipeline_folder
SET workspace_id = (
    SELECT id
    FROM iris_workspace
    WHERE workspace_key = 'default'
);

ALTER TABLE iris_pipeline_folder
    ALTER COLUMN workspace_id SET NOT NULL;

ALTER TABLE iris_pipeline_folder
    ADD CONSTRAINT fk_iris_pipeline_folder_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id);

CREATE INDEX idx_iris_pipeline_folder_workspace_id
    ON iris_pipeline_folder (workspace_id);

ALTER TABLE iris_pipeline
    ADD COLUMN workspace_id BIGINT;

UPDATE iris_pipeline pipeline
SET workspace_id = (
    SELECT folder.workspace_id
    FROM iris_pipeline_folder folder
    WHERE folder.id = pipeline.folder_id
);

ALTER TABLE iris_pipeline
    ALTER COLUMN workspace_id SET NOT NULL;

ALTER TABLE iris_pipeline
    ADD CONSTRAINT fk_iris_pipeline_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id);

CREATE INDEX idx_iris_pipeline_workspace_id
    ON iris_pipeline (workspace_id);

ALTER TABLE iris_pipeline_run
    ADD COLUMN workspace_id BIGINT;

UPDATE iris_pipeline_run pipeline_run
SET workspace_id = (
    SELECT pipeline.workspace_id
    FROM iris_pipeline pipeline
    WHERE pipeline.id = pipeline_run.pipeline_id
);

ALTER TABLE iris_pipeline_run
    ALTER COLUMN workspace_id SET NOT NULL;

ALTER TABLE iris_pipeline_run
    ADD CONSTRAINT fk_iris_pipeline_run_workspace
        FOREIGN KEY (workspace_id) REFERENCES iris_workspace(id);

CREATE INDEX idx_iris_pipeline_run_workspace_id
    ON iris_pipeline_run (workspace_id);

CREATE INDEX idx_iris_pipeline_run_workspace_id_id_desc
    ON iris_pipeline_run (workspace_id, id DESC);
