name: Full Matrix - Source SQL Server

on:
  workflow_dispatch:
  push:
    tags:
      - "benchmark-full-*"
      - "benchmark-sqlserver-*"

permissions:
  contents: write

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark-source-matrix.yml
    with:
      source: sqlserver
